services:
  vector-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vector-database
    volumes:
      - ./output_logs:/app/output_logs
    env_file:
      - .env
    restart: "no"