services:
  customers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-app
    volumes:
      - ./output_logs:/app/output_logs
      - ./dataset:/app/dataset
    restart: "no"